# Generated by Django 5.2.1 on 2025-06-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Demonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=3)),
                ('female', models.CharField(max_length=50)),
                ('male', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cca2', models.CharField(blank=True, max_length=10, null=True)),
                ('cca3', models.CharField(blank=True, max_length=10, null=True)),
                ('ccn3', models.CharField(blank=True, max_length=10, null=True)),
                ('cioc', models.CharField(blank=True, max_length=10, null=True)),
                ('name_common', models.CharField(max_length=100)),
                ('name_official', models.CharField(max_length=100)),
                ('native_name_common', models.CharField(max_length=100)),
                ('native_name_official', models.CharField(max_length=100)),
                ('tld', models.JSONField(default=list)),
                ('independent', models.BooleanField()),
                ('status', models.CharField(max_length=50)),
                ('un_member', models.BooleanField()),
                ('idd_root', models.CharField(max_length=5)),
                ('idd_suffixes', models.JSONField(default=list)),
                ('capital', models.CharField(blank=True, max_length=255, null=True)),
                ('alt_spellings', models.JSONField(default=list)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('subregion', models.CharField(blank=True, max_length=255, null=True)),
                ('latlng', models.JSONField(default=list)),
                ('landlocked', models.BooleanField()),
                ('borders', models.JSONField(default=list)),
                ('area', models.FloatField(blank=True, null=True)),
                ('population', models.BigIntegerField(blank=True, null=True)),
                ('gini', models.JSONField(blank=True, null=True)),
                ('fifa', models.CharField(blank=True, max_length=3, null=True)),
                ('car_signs', models.JSONField(default=list)),
                ('car_side', models.CharField(max_length=10)),
                ('timezones', models.JSONField(default=list)),
                ('continents', models.JSONField(default=list)),
                ('flag_emoji', models.CharField(max_length=10)),
                ('flag_png', models.URLField()),
                ('flag_svg', models.URLField()),
                ('flag_alt', models.TextField()),
                ('coat_of_arms_png', models.URLField()),
                ('coat_of_arms_svg', models.URLField()),
                ('start_of_week', models.CharField(max_length=10)),
                ('capital_latlng', models.JSONField(default=list)),
                ('postal_code_format', models.CharField(blank=True, max_length=255, null=True)),
                ('postal_code_regex', models.CharField(blank=True, max_length=255, null=True)),
                ('google_maps_url', models.URLField()),
                ('openstreet_maps_url', models.URLField()),
                ('currencies', models.ManyToManyField(to='country.currency')),
                ('demonyms', models.ManyToManyField(to='country.demonym')),
                ('languages', models.ManyToManyField(to='country.language')),
            ],
        ),
    ]
